---
engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Syntax:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 30
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    checks:
      wrap-iife:
        enabled: false
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/**/*
- db/**/*
- spec/**/*
- vendor/**/*
- public/**/*
