version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: "postgres"
      - image: circleci/node:4.8.3
    steps:
      - checkout
      - run:
          name: Install Bundle(Fix for failing bundle)
          command: sudo gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Install qt dependencies
          command: sudo apt-get install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-
      - run:
          name: Download PhatomJs
          command: 'sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1'
      - run:
          name: Bundle Install
          command: bundle install
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Copy configuration files
          command: 'cp config/application.yml.example config/application.yml'
          command: 'cp config/database.yml.example config/database.yml'
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Create Database
          command: bundle exec rake db:create
      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace
      # Run rspec in parallel
      - type: shell
        command: bundle exec rspec
      # Save test results for timing analysis
      - store_test_results:
          path: test_results
