- name: "CENTRO DE SEMILIBERDADE DE CRATEÚS"
  street: "Rua Dr. Júlio Lima, 2251"
  district: "Fátima II"
  county: "Crateús"
- name: "CENTRO DE SEMILIBERDADE DE IGUATU"
  street: "Rua José Caeiras, 270"
  district: "Bairro Areias"
  county: "Iguatu"
- name: "CENTRO DE SEMILIBERDADE DE JUAZEIRO DO NORTE"
  street: "Rua Maria Ana Pereira, 925"
  district: "Bairro São João"
  county: "Juazeiro do Norte"
- name: "UNIDADE DE INTERNAÇÃO PROVISÓRIA DE JUAZEIRO DO NORTE"
  street: "Rua Maria Ana Pereira, 925"
  district: "Bairro São João"
  county: "Juazeiro do Norte"
- name: "CENTRO DE SEMILIBERDADE DE SOBRAL"
  street: "Rua Ministro César Cals, 1530"
  district: "Bairro Terrenos Novos"
  county: "Sobral"
- name: "CENTRO DE SEMILIBERDADE MÁRTIR FRANCISCA"
  street: "Rua Euclides Onofre de Sousa, 1550"
  district: "Sapiranga"
  county: "Fortaleza"
- name: "CENTRO EDUCACIONAL ADALCI BARBOSA MOTA"
  street: "Travessa Costa Rica, s/n"
  district: "Padre Andrade"
  county: "Fortaleza"
- name: "CENTRO EDUCACIONAL DOM BOSCO"
  street: "Rua El Dourado, 800"
  district: "Passaré"
  county: "Fortaleza"
- name: "CENTRO EDUCACIONAL PATATIVA DO ASSARÉ"
  street: "Rua Ten. Jurandir Alencar, 2555"
  district: "Ancurí"
  county: "Fortaleza"
- name: "CENTRO SOCIOEDUCATIVO DO CANINDEZINHO"
  street: "Rua José Maurício, s/n"
  district: ""
  county: "Fortaleza"
- name: "CENTRO SOCIOEDUCATIVO DR. ZEQUINHA PARENTE"
  street: "Rua Ministro Cesar Cals"
  district: "Bairro Terrenos Novos"
  county: "Sobral"
- name: "CENTRO EDUCACIONAL SÃO FRANCISCO"
  street: "Rua Menor Jerônimo"
  district: "Passaré"
  county: "Fortaleza"
- name: "CENTRO SOCIOEDUCATIVO DO PASSARÉ"
  street: "Rua Eldourado, 800"
  district: "Passaré"
  county: "Fortaleza"
- name: "CENTRO EDUCACIONAL CARDEAL ALOISIO LORSCHEIDER"
  street: "Rua Ipaumirim, 830"
  district: "José Walter"
  county: "Fortaleza"
- name: "CENTRO EDUCACIONAL SÃO MIGUEL"
  street: "Rua Menor Jerônimo"
  district: "Passaré"
  county: "Fortaleza"
