set :domain, ""
set :port,""
set :deploy_to, ""
set :repository, "git@github.com:CTIGI/JuvOffendersDashboard.git"
set :branch, "master"
set :user, "deploy"
set :rails_env, "production"
set :term_mode,     nil
set :rvm_path, "/usr/local/rvm/bin/rvm"
set :application, "Socioboard-Produção"
set :domain, ""
