set :port, 9898
set :deploy_to, "/var/www/html/juv_offenders_dashboard"
set :repository, "git@github.com:CTIGI/SocioBoard.git"
set :branch, "master"
set :user, "deploy"
set :rails_env, "production"
set :term_mode,     nil
set :rvm_use_path, "/usr/local/rvm/bin/rvm"
set :application, "Socioboard-Homologação"
set :domain, "http://sb.vicegov.ce.gov.br/"
