set :domain, "10.10.0.111"
set :port, 9898
set :deploy_to, "/var/www/html/juv_offenders_dashboard"
set :repository, "git@github.com:CTIGI/JuvOffendersDashboard.git"
set :branch, "master"
set :user, "deploy"
set :rails_env, "production"
set :term_mode,     nil
set :rvm_path, "/usr/local/rvm/bin/rvm"
set :application, "Socioboard-Homologação"
set :domain, "hgsb.vicegov.ce.gov.br"
